### ISSUE TITLE
FF improvements / comparison with GoFF

### ISSUE THREAD

**Issue by gakonst** [arkworks-rs/snark#124]
This was recently released: https://hackmd.io/@zkteam/goff

There might be improvements which we could port over. If not, it'd be useful to benchmark the algebra crate against goff.

https://github.com/iden3/go-iden3-crypto/pull/15
```
this is amazing, just tried now on the Poseidon hash go implementation and just migrating from *big.Int to the code generated by goff is so much faster, as example some benchmark results:
- 1.550.013 ns/op with *big.Int
- 121.748 ns/op with goff generated finite fields arithmetics code
```

**Comment by Pratyush** [comment]
Hmm maybe we should adapt the `zkcrypto/ff-derive` macros with the changes from `GoFF` to automatically generate efficient arithmetic. How much work do you think that would be? Expanding on #31.

**Comment by ValarDragon** [comment]
The key, non-golang specific change seems to be due to a montgomery multiplication optimization they found for modulii with the following properties:
1) Are not mersenne numbers (not 2^n - 1)
2) Don't fully saturate the word size. (If you view the modulus as a c word number, the most significant bit is a 0)

https://hackmd.io/@zkteam/modular_multiplication

The rest of the blog post seems to detail tricks they used for the golang compiler, which seems to involve a lot of looking into what golang code/intrinsics makes the compiler take certain optimizations.

**Comment by Pratyush** [comment]
> Don't fully saturate the word size. (If you view the modulus as a c word number, the most significant bit is a 0)

The good thing is that in Zexe, implicitly all the Fp* types make this assumption already

**Comment by jon-chuang** [comment]
The benchmark seems to be targeted at no assembly. From what I understand, barrettenburg has muls that are 2.5x as fast (~20ns) with x86_64 assembly.

**Comment by jon-chuang** [comment]
I think this issue should be closed.
