### ISSUE TITLE
Serialization Derive Macro does not support Tuples

### ISSUE THREAD

**Issue by gakonst** [arkworks-rs/snark#125]
As title, ref #104. Example:

```rust
#[derive(Debug, CanonicalSerialize)]
struct TestCase<E: PairingEngine> {
    a: (E::G1Affine, E::G1Affine), // this makes the macro fail
    b: E::G1Affine, // this works
    c: Vec<E::G2Affine>, // this works
}
```

It'd be nice if it would just serialize `a.0` followed by `a.1`

Sidenote: In order to use the macro, I had to explicitly import `algebra-core` to my package. It'd be nice if the macro were usable via importing just `algebra` as well.

i.e. go from:
```
zexe_algebra = { package = "algebra", git = "https://github.com/scipr-lab/zexe", version = "0.1.0" }
zexe_algebra_core_derive = { package = "algebra-core-derive", git = "https://github.com/scipr-lab/zexe", version = "0.1.0" }
algebra_core = { package = "algebra-core", git = "https://github.com/scipr-lab/zexe", version = "0.1.0" }
```

to
`zexe_algebra = { package = "algebra", git = "https://github.com/scipr-lab/zexe", version = "0.1.0", features = ["derive"] }`

cc @paberr

**Comment by paberr** [comment]
I'll take a look into it. :)

**Comment by paberr** [comment]
~I opened a PR with the functionality you were looking for.~
Ok, I just noticed that re-exporting it in both algebra and algebra-core results in problems when compiling the tests.

**Comment by paberr** [comment]
So, the problem with not having `algebra-core` as a dependency is:
- The derive macro generates code that refers to types like `::algebra_core::SerializationError`.
- Since `algebra` also re-exports these types, I tried choosing between `algebra_core` and `algebra` using a feature flag at compile time.
- However, since feature flags are active within the whole workspace/project, the following will happen:
    1. Let's suppose you write your own crate that only depends on `algebra` and `gm17`.
    2. You want to use the derive macro using `algebra` only. Then, the feature will be set for the whole workspace. The derive macros will thus use `::algebra::<...>` as a path.
    3. However, gm17/groth16 only depend on `algebra-core`. This will cause `gm17` to not compile anymore.

To avoid this mess, I guess the best way is to still require `algebra-core` as a dependency.
You don't need to explicitly depend on the `algebra-core-derive` anymore, but can use a feature flag in `algebra-core`.

If someone has another idea how to realise this, I'm open for suggestions.

**Comment by gakonst** [comment]
Closing, thank you so much @paberr !
