### ISSUE TITLE
no-std implementation

### ISSUE THREAD

**Issue by mstraka100** [arkworks-rs/snark#16]
Currently zexe is required to compile with the Rust ```std``` library. This is a problem if compiling for certain embedded devices as hardware wallets. A "no-std" implementation not using ```std``` would allow for usability across more devices.

**Comment by Pratyush** [comment]
The difficulty of this depends on the portions that need to be ported to `no_std`; if you're only interested in `algebra`, then this should be relatively painless; you basically only have to redefine a few traits such as `std::error::Error` and `std::io::{Read, Write}`, and to change `Box<dyn std::error::Error>` to a stack-allocated error type.

If however you also wish to perform SNARK proving and setup operations inside an entirely `no_std` environment, then one needs to pull in at least the `alloc` crate, as `Box` and `Vec` are used in various places. This is not too bad because `alloc` still allows use in environments like wasm and SGX.

**Comment by Pratyush** [comment]
This is being worked on in #76
