### ISSUE TITLE
cocks-pinch curve

### ISSUE THREAD

**Issue by amakerofbonnetsandhoods** [arkworks-rs/snark#3]
Hi all,

is the requirement for cocks-pinch method in your scheme to have only a subgroup order equal to the field size of BLS12-377 curve? If so there is a curve with slightly less bits that 782 (766) and with the same embedding degree (6) and the same 2-adicity (3).

Best,

**Comment by Pratyush** [comment]
Yes, that's the only requirement. Do you have more information about the parameters of this curve? And about how you found it? It would help speed up group operations a bit because the base field would require fewer limbs to represent

**Comment by amakerofbonnetsandhoods** [comment]
It is Here are the parameters:

```
q=232904260075757912318819975837786020383098285477643072922161295751284317154430316823047390482960295372117860993792088135317568898127705617804433523909177486818870722491124718283511969751458363038277176745777760356467738308750871961
t=15261201134765176546547561639733805759238658889399327494588326202615797133073971256460451864296526785462165506621499
r=258664426012969094010652733694893533536393512754914660539884262666720468348340822774968888139573360124440321458177
k=6
D=-3
```

where `q` is the field size, `t` the Frobenius trace, `r` the subgroup order, `k` the embedding degree and `D` the complex multiplication discriminant.

**Comment by amakerofbonnetsandhoods** [comment]
It is a short Weierstrass curve (Mordell) constructed via Cocks-pinch method. Here are the parameters:
```
q = 6891450384315732539396789682275657542479668912536150109513790160209623422243491736087683183289411687640864567753786613451161759120554247759349511699125301598951605099378508850372543631423596795951899700429969112842764913119068299
t = 3362637538168598222219435186298528655381674028954528064283340709388076588006567983337308081752755143497537638367248
r = 258664426012969094010652733694893533536393512754914660539884262666720468348340822774968888139573360124440321458177
k = 6
D = -3
```
Where `q` is the field size (761 bits), `t` the Frobenius trace, `r` the subgroup order (BLS12-377 field size), `k` the embedding degree and `D` the complex multiplication discriminant.

And the complex multiplication method gives this elliptic curve equation:
```
y^2 = x^3 + 5428247903343207843304490009542442997117969973913823318164330064320104021081180430153151788629347606889122435541645149581251622306618937027915190165889600280602116819284463614893841480114928247406042232431052188770336204942290254
```

**Comment by Pratyush** [comment]
Sorry for dropping the ball on this, but would you happen to have the script you used to generate the curve on hand? Potentially along with the seed that you used to get these parameters?

Implementing the curve in Zexe requires a few more parameters, like the group generators and the cofactor of the curve. Thanks!

**Comment by Pratyush** [comment]
Using scripts from [ecfactory](https://github.com/scipr-lab/ecfactory), I was able to generate a short Weierstrass curve with the following characteristics:
```
q = 309580009011931014163764297724983378194201666566742408680535581011354362553146634303658290900994169948603982897266486191645717529554042785479035793924285696123643954258759397846181313011452888374107412635812356102447445048219931359
log_2(q) = 766 bits
t = 16813187690842991110773377338432992399274136692210090412357322368057540942120290767635690265010569869968434354192452
r = Bls12_377::q =  258664426012969094010652733694893533536393512754914660539884262666720468348340822774968888139573360124440321458177
k = 6
D = -3
Curve equation: y^2 = x^3 + 1
```

Before implementing this, it would be good to investigate what the nature of `G_2` would be. In more detail, since `D = -3`, which means that one can construct `G_2` as an elliptic curve over `F_q^(k/6) = F_q`.

This improvement, along with the fact that `q` requires 12 64-bit limbs (as opposed to 13 for the current SW6), means that if the details for this curve work out, then one can greatly improve the performance of operations over SW6, resulting in faster proving time.

**Comment by HarryR** [comment]
Hi @Pratyush 

 I'm looking into deriving parameters for a short-Weirstrass curve using the Cocks-Pinch method, but for a curve with a different order - the pairing-friendly BN curve currently used by Ethereum, for example the following parameters operate over a 512-bit field.

```python
k = 6
D = -907
p = 11742173330565941777381011829269014976599312988066932914502311659081591240639663048337636251962463444689811236868741111013936066599878695892673202827159943
# log2(p**k) = 3070.8517564245894
# log2(p) = 511.8086260707649
r = 21888242871839275222246405745257275088696311157297823662689037894645226208583
t = 87552971487357100886781662495880978433366640886365532629781872319700699182367
cofactor = 536460299683217268707818799789652718441558541849210327354091918563867133581519
assert ((p+1)-t) == r*cofactor
a4 = 11100664623344701979115845897135952059428829952785962478618692321069563772474726133750970783114053420254982380136650462295530491902027715564269643905370505
a6 = 2565140083925850561993741347695076936161780532343670156472127466118334156758355878189510773315467934446784708142015206797022779878854638816146870491171631
Fp = GF(p)
E = EllipticCurve(Fp, [0, 0, 0, a4, a6])
```

I can deterministically derive these parameters, and a generator point of order `r`, but I'm having trouble with the other parameters used in `fields/sw6` and `curves/sw6`.

Do you have scripts, pointers or further references I can use to derive the other values? Such as the twist, coefficients and generator for the G2 group. And `FINAL_EXPONENT_LAST_CHUNK_ABS_OF_W0` for example...

I'm really struggling to find a concise reference for this, or any of the tools which were used (aside from `ecfactory`) to derive the generator points and necessary parameters for implementation.

For example, I can create the G2 group over `F_p^k` and its generator:

```python
F6.<a> = GF(p^6)
a_minpoly = a.minpoly()  # x^6 + x^5 + 3*x^4 + 11*x^3 + 44*x^2 + 36*x + 32
E6 = E.base_extend(F6)
assert E6.order() % r == 0
assert E6.order() % cofactor == 0

g2_x = a_minpoly(1)
g2_y2 = g2_x**3 + (a4*g2_x) + a6
g2_y = g2_y2.sqrt()
G2 = E((g2_x, g2_y))
B2 = G2 * cofactor
```

So now we have G1 and G2, and GT in F_p^k* all with r-torsion subgroups (with GT being the r-th roots of unity in F_p^k). What am I missing? Surely the coordinates of G2 are over p^3 rather than p^6?

Your feedback would be deeply appreciated :) 

Note: I could find curves with `D=-3`, but I was unable to calculate the order of the curve in a reasonable amount of time & memory, but larger values of `D` were OK. I modified the `ecfactory` scripts slightly to find only candidates with `log2(p) ~= 512-bits`.

**Comment by Pratyush** [comment]
@HarryR we have some internal scripts that can be used to generate those constants, though you might have to adapt them to your setting. We can share them with you once we clean them up =)

**Comment by HarryR** [comment]
A snippet of code I'm using for deriving curve parameters is: https://gist.github.com/HarryR/fab3bc2aa3df2b36563c98317a4b2375

However I was having trouble with Froebinus coefficients, due to lack of understanding.

**Comment by HarryR** [comment]
I would deeply appreciate if you could share the scripts you have, something that's missing is publicly verifiable and deterministic ways to derive all parameters used in curve constructions, there is a big gap between whitepapers and 'constants used in implementations' where the leap of judgement isn't obvious or is just accepted because 'the implementer derived them, and they work'.

Feel free to email zexe@midnight-labs.org

**Comment by yelhousni** [comment]
> Sorry for dropping the ball on this, but would you happen to have the script you used to generate the curve on hand? Potentially along with the seed that you used to get these parameters?
> 
> Implementing the curve in Zexe requires a few more parameters, like the group generators and the cofactor of the curve. Thanks!

Here is the implementation of the curve https://github.com/EYBlockchain/zk-swap-libff/tree/ey/libff/algebra/curves/sw6_bis
