### ISSUE TITLE
SWJacobian and SWProjective infinity point representation

### ISSUE THREAD

**Issue by 95DDB** [arkworks-rs/snark#44]
I was looking at _algebra/src/curves/models/short_weierstrass_jacobian.rs_ and  _algebra/src/curves/models/short_weierstrass_projective.rs_ and I noticed that:

The implementation of write() method for GroupAffine SWJacobian just serializes the x and y coordinates and, when reading, the read() method reconstructs the infinity flag as:
` x.is_zero && y.is_one() `
In SWProjective, instead, the infinity flag is explicitly written and read. 
So why in jacobian we can safely reconstruct the infinity flag from x and y while in projective, appearently, not ?

Also implementation of _zero()_ and _is_zero()_ functions for GroupProjective looks exactly the same for SWProjective and SWJacobian, but I think that (of course correct me if I'm wrong):

- In Projective, zero point is (0:1:0) and in Jacobian is any point (t^2:t^3:0) as long as t <> 0 (conventionally represented as (1:1:0));
- Because of that, the check that a point is zero implemented as checking that z is zero, should work only in Jacobian but not in Projective. 

What am I missing ?

**Comment by Pratyush** [comment]
Hi! Thanks for filing the issue!.
* Re: `algebra::curves::models::short_weierstrass_jacobian::GroupAffine`, you're right that it's incorrect at the moment. I'll change the `ToBytes` and `FromBytes` impls to match those in `algebra::curves::models::short_weierstrass_projective::GroupAffine`.

* `algebra::curves::models::short_weierstrass_jacobian::Groupprojective::zero()`, you're again right that the zero should be (1:1:0), not (0:1:0). The reason the tests passed was because our `is_zero()` test only checks that `z == 0`, which is always true for representations of zero in both the `Projective` and `Jacobian` cases. 
I'll fix the value of zero and the corresponding check in the `Jacobian` case. You might want to file an issue for this in https://github.com/zkcrypto/bls12_381 and in https://github.com/scipr-lab/libff as well, as that's where we inherited this code from. ([this](https://github.com/zkcrypto/bls12_381/blob/e32494e72011b9811bd7f5c34af5ff6785cc75db/src/g1.rs#L516) and [this](https://github.com/scipr-lab/libff/blob/f2067162520f91438b44e71a2cab2362f1c3cab4/libff/algebra/curves/alt_bn128/alt_bn128_init.cpp#L145) show that the Jacobian coordinates use zero := (0:1:0))

**Comment by 95DDB** [comment]
Thank you very much, will do !

**Comment by 95DDB** [comment]
I think there might be problems also with 
`r1cs_std::groups::curves::short_weierstrass::AffineGadget`
This gadget assumes an Affine representation of a Jacobian point, but here you don't have the infinity flag.
Is it correct to represent zero point in Affine as (0:1) ? In the primitive we have the infinity flag to perform zero-checks, so it's ok, but in the gadget may be wrong or at least not generic (as (0:1), for some curves, can be a regular point), and the infinity flag in get_value() method is reconstructed in the same way for which we said it was not correct in the primitive in read() method.

**Comment by Pratyush** [comment]
Yup, that's what I'm also fixing in PR #45 :)
