### ISSUE TITLE
Conversion between "PrimeField" and "ScalarField"

### ISSUE THREAD

**Issue by Fiono11** [arkworks-rs/snark#95]
How can I convert a type that implements the trait "PrimeField" into the associated type "ScalarField" of the trait "ProjectiveCurve"?

```rust
fn test<F: PrimeField, C: ProjectiveCurve>() {
    let rng = &mut thread_rng();
    let value = F::rand(rng);
    // convert value (F) to value_scalar (<C as algebra::ProjectiveCurve>::ScalarField`)  
    let committed_value = C::prime_subgroup_generator().mul(&value_scalar);
}
```

**Comment by Pratyush** [comment]
You don't need `F` anywhere; you can directly do `let value = C::ScalarField::rand(rng)` (oryou might have to be explicit like so: `let value = <C::ScalarField as UniformRand>::rand(rng)`.

**Comment by 95DDB** [comment]
Hi, I think you can do something like this:
```
fn convert<FromF: PrimeField, ToF: PrimeField>(from: FromF) -> ToF {
    ToF::from_repr(ToF::BigInt::from_bits(from.into_repr().to_bits().as_slice()))
}
```
In this case, `FromF` is your BaseField and `ToF` is your ScalarField (it works also viceversa of course). 
Careful that if `from` is not a valid field element for field `ToF` (i.e. it's over `ToF` modulus), `from_repr()` function will return `ToF::zero()`. You will notice that the two Field elements, the original one and the "converted" one, will have different Montgomery representation (and this is coherent, because the fields are different), but the raw value (and therefore its bit representation) will be the same, and I think that's the use case you are pointing to.
@Pratyush do you agree with this or am I missing something ?

**Comment by Pratyush** [comment]
That should work, but you'll probably have some problems if one field is larger than the other. A simpler way that doesn't involve converting to bits is to use `FromBytes` and `ToBytes`; it's faster than converting to bits.

**Comment by Fiono11** [comment]
That works, thank you to both!
